/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The docblock tags for the hook
 */
export type Tags = Tag[];
/**
 * The list of hooks
 */
export type Hooks = Hook[];

/**
 * The hook representation
 */
export interface Hook {
  /**
   * The hook name
   */
  name: string;
  /**
   * The relative name of the file containing the hook
   */
  file: string;
  /**
   * The line number that the hook starts on within its file
   */
  line: number;
  /**
   * The line number that the hook ends on within its file
   */
  end_line: number;
  /**
   * The hook type
   */
  type: "action" | "filter" | "action_reference" | "filter_reference";
  doc: Doc;
  [k: string]: any;
}
/**
 * The docblock information for the hook
 */
export interface Doc {
  /**
   * The short description as plain text
   */
  description: string;
  /**
   * The long description as markdown
   */
  long_description: string;
  /**
   * The long description as HTML
   */
  long_description_html: string;
  tags: Tags;
  [k: string]: any;
}
/**
 * The docblock tags information for the hook
 */
export interface Tag {
  /**
   * The tag name
   */
  name: "deprecated" | "global" | "ignore" | "link" | "param" | "private" | "return" | "see" | "since" | "todo";
  /**
   * The tag content
   */
  content: string;
  /**
   * Allowed types for parameter values, for @param tags
   */
  types?: string[];
  /**
   * The name of the parameter variable, for @param tags
   */
  variable?: string;
  /**
   * This is only used for @since 3.0.0 MU tags
   */
  description?: string;
  [k: string]: any;
}
